### ISSUE TITLE
HMMsearch issue

### ISSUE THREAD

**Issue by natacha-beck** [BFL-lab/Mfannot#13]
Here is the message from  @JFWolters, reference in #6: 

> I am still getting an error message related to HMMsearch:
> "Error in execution of HMMsearch in RunHMMSearchForLowConservedGenes subroutine"
> 
> Unfortunatley I don't see where this issue is stemming from as both the executables HMMsearchCombiner and HMMsearchWrapper are in my PATH, as well as all the executables from HMMER.
> 
> I have included another test run using the version of mfannot linked in your most recent reply, which I saved as mfannot_test_091918.
> 
> This run was done using the command:
> mfannot_test_091918 --d --T ~/packages/Mfannot-master/examples/mfannot_test_09192018 allomyces.fna >& mfannot_log

**Comment by natacha-beck** [comment]
@JFWolters: Can you please provide me the temporary directory to take a look.

**Comment by JFWolters** [comment]
My apologies I forgot to attach it.
[mfannot_test_09192018.zip](https://github.com/BFL-lab/Mfannot/files/2401642/mfannot_test_09192018.zip)

**Comment by natacha-beck** [comment]
Can you please test the following: 

- Go in `mfannot_test_09192018/contig/contig1/`
- Run the following command: `getorf contig1.faa -table 4 -outseq contig1.orf`

Can you let me know what is your result. 
I expect that you get an error, I do not see the contig1.orf in your temporary directory.

**Comment by JFWolters** [comment]
You are correct, when I run that command I get the following error message:

getorf: error while loading shared libraries: libnucleus.so.6: cannot open shared object file: No such file or directory

**Comment by natacha-beck** [comment]
Did you try that: 

https://www.biostars.org/p/86327/

**Comment by JFWolters** [comment]
I am going to have to follow up on this in a bit because I was not the one to install EMBOSS on the system I am using. I am trying to get MFANNOT running on a shared campus server (which unfortunately doesn't support installation through a Docker) and EMBOSS had previously been installed on that system. I will be contacting the system administrators and trying to sort this out.

**Comment by JFWolters** [comment]
After some back and forth with system administrators it is clear that this issue was caused by problems with the system's EMBOSS installation which required changing a few of the EMBOSS environmental variables.

After fixing those, no more errors remain during execution of MFANNOT and everything appears to be showing up in the masterfile now.

Thank you so much for all your help!

**Comment by natacha-beck** [comment]
Happy to know that everything is know fixed. 

Thanks to you too.
