### ISSUE TITLE
Extensive "Use of unitialized value" errors, tRNAs not annoted

### ISSUE THREAD

**Issue by JFWolters** [BFL-lab/Mfannot#6]
I was able to get the package running and it will annotate protein coding features and ribosomal RNAs but the tRNAs are not appearing in the annotation.

During execution, a very large number of error messages are generated

I have attached a log file generated by running "mfannot -d -g 3 allomyces.fna >& debug.log" along with the results *.new file. Added a *.txt extension due to github requirements.
[debug.log.txt](https://github.com/BFL-lab/Mfannot/files/2333018/debug.log.txt)

[allomyces.fna.new.txt](https://github.com/BFL-lab/Mfannot/files/2333017/allomyces.fna.new.txt)

No other output files were generated so I will be looking further into why the *.sqn files are absent.

**Comment by JFWolters** [comment]
Thank you for the clarification on the sqn format.

Here is the requested folder generated by running the following command:
mfannot --d --T ~/packages/Mfannot-master/examples/mfannot-test allomyces.fna >& mfannot_log
[mfannot-test.zip](https://github.com/BFL-lab/Mfannot/files/2336618/mfannot-test.zip)

**Comment by natacha-beck** [comment]
@JFWolters I took a look to your issue. 

The first issue happens when Mfannot parse the Blast output, I can see that you used BLASTP 2.6.0+ when I used a previous version of BLASTP 2.2.31+. 

At this point it does not explain the difference and the following message: 
> Use of uninitialized value $strand in string eq at ... line 1056, <GEN354> line 173912.

I suspect an issue when Mfannot parse the `Blastoutput.xml` can you please add the following: 

`
print "rdesc: $rdesc\n";
`

Just before the line 1056 and send me the trace. 

Mfannot is not able to parse the result and to extract the `strand`, we need to define why.

**Comment by natacha-beck** [comment]
And for the tRNA the issue came from RNAfinder, when I look at the stderr of RNAfinder I can see the following: 

> The config file '.RNAfinder.cfg' doesn't find. Check your installation for this one.

Please read the README of RNAfinder [here](https://github.com/BFL-lab/RNAfinder) and take care of the `.RNAfinder.cfg` config file, you  need o put this one in your $HOME

**Comment by JFWolters** [comment]
Thank you for the feedback, I had missed that line in the RNAfinder readme.

I renamed the DOT_RNfinder.cfg as .RNAfinder.cfg and set the RNAFINDER_CFG_PATH to point to the directory containing it. I also copied the file to my home directory just to be doubly sure.

I then added the requested line in between lines 1055 and 1056.

I ran mfannot as follows:
mfannot --d --T ~/packages/Mfannot-master/examples/mfannot_test2 allomyces.fna >& mfannot_log

Ive attached the specified work directory.
[mfannot_test2.zip](https://github.com/BFL-lab/Mfannot/files/2357949/mfannot_test2.zip)

**Comment by natacha-beck** [comment]
@JFWolters : 

At this point I still see an issue with the RNA annotation. If I look in the stderr of the RNAfinder I see the following message: 

> No path for ErpinModels were found
  
To solve this issue you need to download the following data: 

> https://github.com/BFL-lab/MFannot_data 

And set the `ERPIN_MOD_PATH` variable to `MFannot_data/models/Erpin_models`.

**Comment by natacha-beck** [comment]
@JFWolters Can you download the latest version of MFannot: 

- https://github.com/BFL-lab/Mfannot/blob/master/mfannot 

This version should fix the issue of all the uninitialised value. It was due to a difference of output in the new version of BLAST. I just simplified a regex to be compliant to both version.

**Comment by JFWolters** [comment]
Thank you for all the assistance. With the new version of MFANNOT I am not getting the error messages anymore. I am still having an issue annotating tRNAs after downloading the lastest version and fixing my ErpinModels path (I had forgetten the "models" part of the path, a lot of user errors on my part here, I apologize for the trouble). It is likely still an error on my part, but I have checked the paths again and do not see the issue. Any further help would be greatly appreciated.

I have run the new version with the following command and attached the output:
mfannot --d --T ~/packages/Mfannot-master/examples/mfannot_test3 allomyces.fna >& mfannot_log

[mfannot_test3.zip](https://github.com/BFL-lab/Mfannot/files/2376745/mfannot_test3.zip)

**Comment by JFWolters** [comment]
Hello,

Thank you again for all your help. Based on your suggestions I was able to diagnose the issue that was causing tRNAs not be annotated. 

Running RNAfinder pointed me to an issue with erpin. I had not pathed erpin correctly, due to the installation containing only the executables erpin32 and erpin64. I put erpin64 in my PATH as erpin and now trRNAs are being annotated.

I am still getting an error message related to HMMsearch:
"Error in execution of HMMsearch in RunHMMSearchForLowConservedGenes subroutine"

Unfortunatley I don't see where this issue is stemming from as both the executables HMMsearchCombiner and HMMsearchWrapper are in my PATH, as well as all the executables from HMMER.

I have included another test run using the version of mfannot linked in your most recent reply, which I saved as mfannot_test_091918.

This run was done using the command:
mfannot_test_091918 --d --T ~/packages/Mfannot-master/examples/mfannot_test_09192018 allomyces.fna >& mfannot_log

**Comment by natacha-beck** [comment]
Hi @JFWolters, I will closed this issue since both of the first issue is now solved (The one related to BLAST and the related to RNA identification). 

I have created a new issue mentioning the HMMsearch issue [here](https://github.com/BFL-lab/Mfannot/issues/13) (In order to keep track of the different issues.)
